version: '3'

services:
  stub:
    image: mountebank
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mountebank
    ports:
      - "2525:2525"
      - "3000-3010:3000-3010" # for the imposters (potentially multiple)
